<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('StateList', 'doctrine');

/**
 * BaseStateList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $state_name
 * @property integer $country_id
 * 
 * @method integer   getId()         Returns the current record's "id" value
 * @method string    getStateName()  Returns the current record's "state_name" value
 * @method integer   getCountryId()  Returns the current record's "country_id" value
 * @method StateList setId()         Sets the current record's "id" value
 * @method StateList setStateName()  Sets the current record's "state_name" value
 * @method StateList setCountryId()  Sets the current record's "country_id" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStateList extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('state_list');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('state_name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('country_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}