<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Credential', 'doctrine');

/**
 * BaseCredential
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $credential
 * 
 * @method integer    getId()         Returns the current record's "id" value
 * @method string     getCredential() Returns the current record's "credential" value
 * @method Credential setId()         Sets the current record's "id" value
 * @method Credential setCredential() Sets the current record's "credential" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCredential extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('credential');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('credential', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}