<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('HotList', 'doctrine');

/**
 * BaseHotList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $member_id
 * @property integer $posting_id
 * @property Postings $Postings
 * @property Member $Member
 * 
 * @method integer  getId()         Returns the current record's "id" value
 * @method integer  getMemberId()   Returns the current record's "member_id" value
 * @method integer  getPostingId()  Returns the current record's "posting_id" value
 * @method Postings getPostings()   Returns the current record's "Postings" value
 * @method Member   getMember()     Returns the current record's "Member" value
 * @method HotList  setId()         Sets the current record's "id" value
 * @method HotList  setMemberId()   Sets the current record's "member_id" value
 * @method HotList  setPostingId()  Sets the current record's "posting_id" value
 * @method HotList  setPostings()   Sets the current record's "Postings" value
 * @method HotList  setMember()     Sets the current record's "Member" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHotList extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hot_list');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('member_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('posting_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Postings', array(
             'local' => 'posting_id',
             'foreign' => 'id'));

        $this->hasOne('Member', array(
             'local' => 'member_id',
             'foreign' => 'id'));
    }
}