<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FriendshipStatus', 'doctrine');

/**
 * BaseFriendshipStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $status_code
 * @property string $description
 * 
 * @method integer          getId()          Returns the current record's "id" value
 * @method string           getStatusCode()  Returns the current record's "status_code" value
 * @method string           getDescription() Returns the current record's "description" value
 * @method FriendshipStatus setId()          Sets the current record's "id" value
 * @method FriendshipStatus setStatusCode()  Sets the current record's "status_code" value
 * @method FriendshipStatus setDescription() Sets the current record's "description" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFriendshipStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('friendship_status');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('status_code', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('description', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}