<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SurveyResults', 'doctrine');

/**
 * BaseSurveyResults
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $question_id
 * @property string $result
 * @property timestamp $action_timestamp
 * @property integer $raters_group_id
 * @property RatersGroup $RatersGroup
 * 
 * @method integer       getId()               Returns the current record's "id" value
 * @method integer       getQuestionId()       Returns the current record's "question_id" value
 * @method string        getResult()           Returns the current record's "result" value
 * @method timestamp     getActionTimestamp()  Returns the current record's "action_timestamp" value
 * @method integer       getRatersGroupId()    Returns the current record's "raters_group_id" value
 * @method RatersGroup   getRatersGroup()      Returns the current record's "RatersGroup" value
 * @method SurveyResults setId()               Sets the current record's "id" value
 * @method SurveyResults setQuestionId()       Sets the current record's "question_id" value
 * @method SurveyResults setResult()           Sets the current record's "result" value
 * @method SurveyResults setActionTimestamp()  Sets the current record's "action_timestamp" value
 * @method SurveyResults setRatersGroupId()    Sets the current record's "raters_group_id" value
 * @method SurveyResults setRatersGroup()      Sets the current record's "RatersGroup" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSurveyResults extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('survey_results');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('question_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('result', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('action_timestamp', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('raters_group_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RatersGroup', array(
             'local' => 'raters_group_id',
             'foreign' => 'id'));
    }
}