<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MembershipStatus', 'doctrine');

/**
 * BaseMembershipStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $description
 * 
 * @method integer          getId()          Returns the current record's "id" value
 * @method string           getDescription() Returns the current record's "description" value
 * @method MembershipStatus setId()          Sets the current record's "id" value
 * @method MembershipStatus setDescription() Sets the current record's "description" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMembershipStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('membership_status');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('description', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}