<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SurveyComments', 'doctrine');

/**
 * BaseSurveyComments
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $rater_group_id
 * @property integer $member_id
 * @property string $comments
 * @property RatersGroup $RatersGroup
 * @property Member $Member
 * 
 * @method integer        getId()             Returns the current record's "id" value
 * @method integer        getRaterGroupId()   Returns the current record's "rater_group_id" value
 * @method integer        getMemberId()       Returns the current record's "member_id" value
 * @method string         getComments()       Returns the current record's "comments" value
 * @method RatersGroup    getRatersGroup()    Returns the current record's "RatersGroup" value
 * @method Member         getMember()         Returns the current record's "Member" value
 * @method SurveyComments setId()             Sets the current record's "id" value
 * @method SurveyComments setRaterGroupId()   Sets the current record's "rater_group_id" value
 * @method SurveyComments setMemberId()       Sets the current record's "member_id" value
 * @method SurveyComments setComments()       Sets the current record's "comments" value
 * @method SurveyComments setRatersGroup()    Sets the current record's "RatersGroup" value
 * @method SurveyComments setMember()         Sets the current record's "Member" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSurveyComments extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('survey_comments');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('rater_group_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('member_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('comments', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RatersGroup', array(
             'local' => 'rater_group_id',
             'foreign' => 'id'));

        $this->hasOne('Member', array(
             'local' => 'member_id',
             'foreign' => 'id'));
    }
}