<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('HangoutStatus', 'doctrine');

/**
 * BaseHangoutStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Hangout
 * 
 * @method integer             getId()      Returns the current record's "id" value
 * @method string              getName()    Returns the current record's "name" value
 * @method Doctrine_Collection getHangout() Returns the current record's "Hangout" collection
 * @method HangoutStatus       setId()      Sets the current record's "id" value
 * @method HangoutStatus       setName()    Sets the current record's "name" value
 * @method HangoutStatus       setHangout() Sets the current record's "Hangout" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHangoutStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hangout_status');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Hangout', array(
             'local' => 'id',
             'foreign' => 'hangout_status_id'));
    }
}