<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ZipcodeList', 'doctrine');

/**
 * BaseZipcodeList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $zipcode
 * @property integer $state_id
 * 
 * @method integer     getId()       Returns the current record's "id" value
 * @method integer     getZipcode()  Returns the current record's "zipcode" value
 * @method integer     getStateId()  Returns the current record's "state_id" value
 * @method ZipcodeList setId()       Sets the current record's "id" value
 * @method ZipcodeList setZipcode()  Sets the current record's "zipcode" value
 * @method ZipcodeList setStateId()  Sets the current record's "state_id" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseZipcodeList extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('zipcode_list');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('zipcode', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('state_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}