<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Profile', 'doctrine');

/**
 * BaseProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $order_number
 * @property integer $profile_input_type_id
 * @property integer $has_custom_style
 * @property integer $placement_id
 * @property ProfileInputType $ProfileInputType
 * @property Doctrine_Collection $MemberProfile
 * @property Doctrine_Collection $ProfileChoice
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method string              getName()                  Returns the current record's "name" value
 * @method integer             getOrderNumber()           Returns the current record's "order_number" value
 * @method integer             getProfileInputTypeId()    Returns the current record's "profile_input_type_id" value
 * @method integer             getHasCustomStyle()        Returns the current record's "has_custom_style" value
 * @method integer             getPlacementId()           Returns the current record's "placement_id" value
 * @method ProfileInputType    getProfileInputType()      Returns the current record's "ProfileInputType" value
 * @method Doctrine_Collection getMemberProfile()         Returns the current record's "MemberProfile" collection
 * @method Doctrine_Collection getProfileChoice()         Returns the current record's "ProfileChoice" collection
 * @method Profile             setId()                    Sets the current record's "id" value
 * @method Profile             setName()                  Sets the current record's "name" value
 * @method Profile             setOrderNumber()           Sets the current record's "order_number" value
 * @method Profile             setProfileInputTypeId()    Sets the current record's "profile_input_type_id" value
 * @method Profile             setHasCustomStyle()        Sets the current record's "has_custom_style" value
 * @method Profile             setPlacementId()           Sets the current record's "placement_id" value
 * @method Profile             setProfileInputType()      Sets the current record's "ProfileInputType" value
 * @method Profile             setMemberProfile()         Sets the current record's "MemberProfile" collection
 * @method Profile             setProfileChoice()         Sets the current record's "ProfileChoice" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profile');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('order_number', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('profile_input_type_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('has_custom_style', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('placement_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ProfileInputType', array(
             'local' => 'profile_input_type_id',
             'foreign' => 'id'));

        $this->hasMany('MemberProfile', array(
             'local' => 'id',
             'foreign' => 'profile_id'));

        $this->hasMany('ProfileChoice', array(
             'local' => 'id',
             'foreign' => 'profile_id'));
    }
}