<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PrivateMessageReceiver', 'doctrine');

/**
 * BasePrivateMessageReceiver
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $receiver_id
 * @property integer $private_message_id
 * 
 * @method integer                getId()                 Returns the current record's "id" value
 * @method integer                getReceiverId()         Returns the current record's "receiver_id" value
 * @method integer                getPrivateMessageId()   Returns the current record's "private_message_id" value
 * @method PrivateMessageReceiver setId()                 Sets the current record's "id" value
 * @method PrivateMessageReceiver setReceiverId()         Sets the current record's "receiver_id" value
 * @method PrivateMessageReceiver setPrivateMessageId()   Sets the current record's "private_message_id" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePrivateMessageReceiver extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('private_message_receiver');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('receiver_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('private_message_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}