<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UserCredential', 'doctrine');

/**
 * BaseUserCredential
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $credential_id
 * @property integer $user_id
 * 
 * @method integer        getId()            Returns the current record's "id" value
 * @method integer        getCredentialId()  Returns the current record's "credential_id" value
 * @method integer        getUserId()        Returns the current record's "user_id" value
 * @method UserCredential setId()            Sets the current record's "id" value
 * @method UserCredential setCredentialId()  Sets the current record's "credential_id" value
 * @method UserCredential setUserId()        Sets the current record's "user_id" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserCredential extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_credential');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('credential_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}