<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PrivateMessage', 'doctrine');

/**
 * BasePrivateMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $subject
 * @property string $message
 * @property timestamp $date
 * @property integer $sender_id
 * 
 * @method integer        getId()        Returns the current record's "id" value
 * @method string         getSubject()   Returns the current record's "subject" value
 * @method string         getMessage()   Returns the current record's "message" value
 * @method timestamp      getDate()      Returns the current record's "date" value
 * @method integer        getSenderId()  Returns the current record's "sender_id" value
 * @method PrivateMessage setId()        Sets the current record's "id" value
 * @method PrivateMessage setSubject()   Sets the current record's "subject" value
 * @method PrivateMessage setMessage()   Sets the current record's "message" value
 * @method PrivateMessage setDate()      Sets the current record's "date" value
 * @method PrivateMessage setSenderId()  Sets the current record's "sender_id" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePrivateMessage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('private_message');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('subject', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('message', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('sender_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}