<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RequestStatus', 'doctrine');

/**
 * BaseRequestStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $status_code
 * @property string $description
 * @property Doctrine_Collection $Requester
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getStatusCode()  Returns the current record's "status_code" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method Doctrine_Collection getRequester()   Returns the current record's "Requester" collection
 * @method RequestStatus       setId()          Sets the current record's "id" value
 * @method RequestStatus       setStatusCode()  Sets the current record's "status_code" value
 * @method RequestStatus       setDescription() Sets the current record's "description" value
 * @method RequestStatus       setRequester()   Sets the current record's "Requester" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRequestStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('request_status');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('status_code', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('description', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Requester', array(
             'local' => 'id',
             'foreign' => 'request_status_id'));
    }
}