<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Messages', 'doctrine');

/**
 * BaseMessages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $member_id
 * @property integer $sender_id
 * @property string $message
 * @property integer $is_read
 * @property timestamp $date_read
 * @property integer $posting_id
 * @property integer $is_friend
 * @property timestamp $date_created
 * 
 * @method integer   getId()           Returns the current record's "id" value
 * @method integer   getMemberId()     Returns the current record's "member_id" value
 * @method integer   getSenderId()     Returns the current record's "sender_id" value
 * @method string    getMessage()      Returns the current record's "message" value
 * @method integer   getIsRead()       Returns the current record's "is_read" value
 * @method timestamp getDateRead()     Returns the current record's "date_read" value
 * @method integer   getPostingId()    Returns the current record's "posting_id" value
 * @method integer   getIsFriend()     Returns the current record's "is_friend" value
 * @method timestamp getDateCreated()  Returns the current record's "date_created" value
 * @method Messages  setId()           Sets the current record's "id" value
 * @method Messages  setMemberId()     Sets the current record's "member_id" value
 * @method Messages  setSenderId()     Sets the current record's "sender_id" value
 * @method Messages  setMessage()      Sets the current record's "message" value
 * @method Messages  setIsRead()       Sets the current record's "is_read" value
 * @method Messages  setDateRead()     Sets the current record's "date_read" value
 * @method Messages  setPostingId()    Sets the current record's "posting_id" value
 * @method Messages  setIsFriend()     Sets the current record's "is_friend" value
 * @method Messages  setDateCreated()  Sets the current record's "date_created" value
 * @property  $
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMessages extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('messages');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('member_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('sender_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('message', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('is_read', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('date_read', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('posting_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('is_friend', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('date_created', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Member', array(
             'local' => 'sender_id',
             'foreign' => 'id'));
    }
}