<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Questions', 'doctrine');

/**
 * BaseQuestions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $questions
 * @property integer $answer_type
 * @property integer $is_average
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method string    getQuestions()   Returns the current record's "questions" value
 * @method integer   getAnswerType()  Returns the current record's "answer_type" value
 * @method integer   getIsAverage()   Returns the current record's "is_average" value
 * @method Questions setId()          Sets the current record's "id" value
 * @method Questions setQuestions()   Sets the current record's "questions" value
 * @method Questions setAnswerType()  Sets the current record's "answer_type" value
 * @method Questions setIsAverage()   Sets the current record's "is_average" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuestions extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('questions');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('questions', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('answer_type', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('is_average', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}