<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CountryList', 'doctrine');

/**
 * BaseCountryList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $country_name
 * 
 * @method integer     getId()           Returns the current record's "id" value
 * @method string      getCountryName()  Returns the current record's "country_name" value
 * @method CountryList setId()           Sets the current record's "id" value
 * @method CountryList setCountryName()  Sets the current record's "country_name" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCountryList extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('country_list');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('country_name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}