<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Music', 'doctrine');

/**
 * BaseMusic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $artist_name
 * @property timestamp $created_at
 * @property integer $genre_id
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method string    getName()        Returns the current record's "name" value
 * @method string    getArtistName()  Returns the current record's "artist_name" value
 * @method timestamp getCreatedAt()   Returns the current record's "created_at" value
 * @method integer   getGenreId()     Returns the current record's "genre_id" value
 * @method Music     setId()          Sets the current record's "id" value
 * @method Music     setName()        Sets the current record's "name" value
 * @method Music     setArtistName()  Sets the current record's "artist_name" value
 * @method Music     setCreatedAt()   Sets the current record's "created_at" value
 * @method Music     setGenreId()     Sets the current record's "genre_id" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMusic extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('music');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('artist_name', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('genre_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}