<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ProfileChoice', 'doctrine');

/**
 * BaseProfileChoice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $choice_name
 * @property integer $order_number
 * @property integer $profile_id
 * @property Profile $Profile
 * @property Doctrine_Collection $MemberProfile
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getChoiceName()    Returns the current record's "choice_name" value
 * @method integer             getOrderNumber()   Returns the current record's "order_number" value
 * @method integer             getProfileId()     Returns the current record's "profile_id" value
 * @method Profile             getProfile()       Returns the current record's "Profile" value
 * @method Doctrine_Collection getMemberProfile() Returns the current record's "MemberProfile" collection
 * @method ProfileChoice       setId()            Sets the current record's "id" value
 * @method ProfileChoice       setChoiceName()    Sets the current record's "choice_name" value
 * @method ProfileChoice       setOrderNumber()   Sets the current record's "order_number" value
 * @method ProfileChoice       setProfileId()     Sets the current record's "profile_id" value
 * @method ProfileChoice       setProfile()       Sets the current record's "Profile" value
 * @method ProfileChoice       setMemberProfile() Sets the current record's "MemberProfile" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfileChoice extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profile_choice');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('choice_name', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('order_number', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('profile_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profile', array(
             'local' => 'profile_id',
             'foreign' => 'id'));

        $this->hasMany('MemberProfile', array(
             'local' => 'id',
             'foreign' => 'profile_choice_id'));
    }
}