<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/04/25 08:48:44

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=hangout',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
