<?php

/**
 * AnswerTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnswerTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnswerTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AnswerType');
    }
}