<?php

/**
 * CountryListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CountryListTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CountryListTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CountryList');
    }
}