<?php

/**
 * FriendshipStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FriendshipStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FriendshipStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FriendshipStatus');
    }
}