<?php

/**
 * Friendship
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Friendship extends BaseFriendship
{
    public static function addFriend($rater_group_id)
    {
        try{
            $q = Doctrine::getTable('RatersGroup')->findOneBy("id", $rater_group_id);

            $friendship = new Friendship();
            $friendship->setMemberId($q->rater);
            $friendship->setFriendId($q->ratee);
            $friendship->setStatus(1);
            $friendship->save();
        }catch(Exception $e){
            die($e->getMessage());
        }
    }   
    
    public static function getFriendRequests($friend_id)
    {        
        try{
            return $result = 
                    Doctrine_Manager::getInstance()->connection()->
                    execute("SELECT
                                DISTINCT 
                                    f.id as friendship_id, 
                                    f.status as friendship_status_id,
                                    fs.description as friendship_status, 
                                    m.*,
                                    p.*
                            FROM friendship f
                            JOIN member m ON f.member_id = .m.id
                            JOIN photo p ON m.profile_picture_id = p.id
                            JOIN friendship_status fs ON f.status = fs.id
                            WHERE f.friend_id = $friend_id")
                    ->fetchAll();	
         }catch(Exception $e){
            return $e->getMessage();
        }
    }
   
    public static function getFriends($member_id)
    {        
        if(is_null($member_id))
        {
            throw new Exception('Member Id cannot be null.');
        }
        
        try{
            return $result = 
                    Doctrine_Manager::getInstance()->connection()->
                    execute("SELECT 
                                f.id as friend_id,
                                m1.nick_name,
                                p1.path,
                                m1.email,
                                m1.id,
                                m1.profile_id,
                                m1.gender
                            FROM `friendship` f 
                            JOIN member m1 on f.friend_id = m1.id                            
                            LEFT JOIN photo p1 on m1.id = p1.member_id AND m1.profile_picture_id = p1.id
                            WHERE f.member_id = $member_id and f.status = 2")
                   ->fetchAll();	
         }catch(Exception $e){
            return $e->getMessage();
        }
    }
    
    public static function updateRequestStatus($stat = null,$friendship_id = null)
    {
        $q = Doctrine::getTable('Friendship')->findOneBy("id", $friendship_id);
        $q->status = ($stat == 'approve')? 2:3;
        $q->save();
    }
    
    public static function unfriend($friendshipId = null)
    {
        try{
            $q = Doctrine::getTable('Friendship')->findOneBy("id", $friendshipId);
            if($q)
                $q->delete();
            return true;
        }catch(Exception $e){
            return $e->getMessage();
        }        
    }
    
//    public function getFriends($member_id = null)
//    {       
//        if(is_null($memberId))
//        {
//            throw new Exception('Member Id cannot be null.');
//        }
//        try{
//            return $result = 
//            Doctrine_Manager::getInstance()->connection()->
//                  execute("SELECT 
//                            m1.nick_name,
//                            p1.path,
//                            m1.email,
//                            m1.id,
//                            m1.profile_id
//                        FROM friendship f 
//                        JOIN member m1 on f.friend_id = m1.id
//                        JOIN member m2 on f.member_id = m2.id
//                        LEFT JOIN photo p1 on m1.id = p1.member_id AND m1.profile_picture_id = p1.id
//                        WHERE f.member_id = $memberId and f.status = 2")
//                    ->fetchAll();
            
//            return $result = 
//                    Doctrine_Manager::getInstance()->connection()->
//                    execute("SELECT
//                                DISTINCT 
//                                    f.id as friendship_id, 
//                                    f.status as friendship_status_id,
//                                    fs.description as friendship_status, 
//                                    m.*,
//                                    p.*
//                            FROM friendship f
//                            JOIN member m ON f.member_id = .m.id
//                            JOIN photo p ON m.profile_picture_id = p.id
//                            JOIN friendship_status fs ON f.status = fs.id
//                            WHERE f.friend_id = $member_id")
//                    ->fetchAll();
//        }catch(Exception $e){
//            return $e->getMessage();
//        }        
//    }
            
}