<?php

/**
 * HangoutTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HangoutTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HangoutTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Hangout');
    }
}