<?php

/**
 * HangoutStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HangoutStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HangoutStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HangoutStatus');
    }
}