<?php

/**
 * HotListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HotListTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HotListTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HotList');
    }
}