<?php

/**
 * MemberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MemberTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MemberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Member');
    }
    
    public function getMemberInfo($id,$byProfileId = false)
    {
        if(is_null($id))
        {
            throw new Exception('Id cannot be null');
        }
        else
        {
            $stmt  = 'm.id, m.username, m.nick_name, m.country, m.state, m.city, m.email,';
            $stmt .= 'm.age, m.zip_code, m.gender, m.birthday, m.profile_picture_id';
            
            if($byProfileId)
            {                
                $result = $this->createQuery()
                                ->select($stmt)->from('Member m')
                                ->where('m.profile_id = ?',$id)->limit(1)->fetchArray();
            }
            else
            {
                $result = $this->createQuery()
                                ->select($stmt)->from('Member m')
                                ->where('m.id = ?',$id)->limit(1)->fetchArray();
            }
            
            return $result;
        }
    }
    
    public function getMemberProfileInfo($memberId, $is_profile_id)
    {
        if(is_null($memberId))
        {
            throw new Exception('MemberId cannot be null');
        }
        else
        {
            if($is_profile_id)
            {
                $result = $this->createQuery()->select('*')->from('member')->where('profile_id = ?', $memberId)->fetchArray();//profile id
                $memberId = $result[0]['id'];
            }
            
            $result = $this->createQuery()
                    ->select('p.name, i.object_name, p.profile_input_type_id, p.placement_id, m.value, c.choice_name, p.order_number')->distinct()
                    ->from('Profile p')
                    ->leftJoin('p.MemberProfile m')
                    ->leftJoin('m.ProfileChoice c')
                    ->leftJoin('p.ProfileInputType i')                    
                    ->where('m.member_id = ?',$memberId)       
                    ->orderBy('p.placement_id, p.order_number')
                    ->fetchArray();
            
            if(count($result) == 0)
            {
                $result = $this->createQuery()
                    ->select("p.name, i.object_name, p.profile_input_type_id, p.placement_id, p.order_number")->distinct()
                    ->from('Profile p')
                    ->leftJoin('p.ProfileInputType i')                    
                    ->orderBy('p.placement_id, p.order_number')
                    ->fetchArray();
            }
            
//            print '<pre>';
//            die(print_r($result));
            return $result;
        }
    }
}