<?php

/**
 * MusicTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MusicTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MusicTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Music');
    }
}