<?php

/**
 * PolicyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PolicyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PolicyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Policy');
    }
}