<?php

/**
 * PostingsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostingsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostingsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Postings');
    }
    
    public static function getPostings()
    {
        return self::getInstance()->createQuery('p');
    }
}