<?php

/**
 * PrivateMessageReceiverTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PrivateMessageReceiverTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PrivateMessageReceiverTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PrivateMessageReceiver');
    }
}