<?php

/**
 * PrivateMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PrivateMessageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PrivateMessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PrivateMessage');
    }
}