<?php

/**
 * ProfileChoiceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileChoiceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileChoiceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileChoice');
    }
}