<?php

/**
 * ProfileInputTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileInputTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileInputTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileInputType');
    }
}