<?php

/**
 * RequestStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RequestStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RequestStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RequestStatus');
    }
}