<?php

/**
 * StateListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StateListTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StateListTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StateList');
    }
}