<?php

/**
 * SurveyComments
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SurveyComments extends BaseSurveyComments
{
    public static function saveComments($data = array())
    {
        $surveyComments = new SurveyComments();
        $surveyComments->setRaterGroupId($data['rater_group_id']);
        $surveyComments->setMemberId($data['member_id']);
        $surveyComments->setComments($data['comments']);
        $surveyComments->save();
        
        $q = Doctrine::getTable('RatersGroup')->findOneBy("id", $data['rater_group_id']);
        $q->counter_done = ($q->counter_done + 1);
        $q->save();
    }
    
    public static function getHangoutComments($posting_id)
    {
        $q = SurveyCommentsTable::getInstance()->createQuery('sc');
        $q->innerJoin('sc.RatersGroup rg');
        $q->innerJoin('sc.Member m');
        $q->where('rg.posting_id = ?', $posting_id);        
        return $q->execute();
    }
    
}