<?php

/**
 * SurveyCommentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SurveyCommentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SurveyCommentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SurveyComments');
    }
}