<?php

/**
 * SurveyResultsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SurveyResultsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SurveyResultsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SurveyResults');
    }
}