<?php

/**
 * UserCredentialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserCredentialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserCredentialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserCredential');
    }
}