<?php

/**
 * ZipcodeListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ZipcodeListTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ZipcodeListTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ZipcodeList');
    }
}