<?php

/**
 * ZipsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ZipsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ZipsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Zips');
    }
}